
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: thaihocapp_development
  host: db
  username: web
  password: 123
test:
  <<: *default
  database: thaihocapp_test
production:
  <<: *default
  database: thaihocapp_production
  username: thaihocapp
  password: <%= ENV['THAIHOCAPP_DATABASE_PASSWORD'] %>
